### ISSUE TITLE
Email registration

### ISSUE THREAD

**Issue by carlesandres** [vim-conf-live/NeoVimconf-site-2022#11]

**Comment by mvargasmoran** [comment]
last years registration was made using the userbase service as explained in last year site repo.

https://github.com/vim-conf-live/vim-conf-live-2021

Keeping userbase will make @AdamBD life easier as he already used it last year.

**Comment by mvargasmoran** [comment]
@AdamBD do we have any changes for configuring userbase?
if not we can just take the implementation from last year website.
or maybe you want to try another service.
