### ISSUE TITLE
Add Code of Conduct page

### ISSUE THREAD

**Issue by mvargasmoran** [vim-conf-live/NeoVimconf-site-2022#27]
We need this for attendees.
Last year the link was incorporated to registration form, as to call the attention of the user to it.
Maybe now we can do the same, but also do the good ole checkbox accepting and validating for it before submitting the registration.

**Comment by AdamBD** [comment]
This is the content we should use: https://github.com/vim-conf-live/vim-conf-live-2021/blob/main/pages/code-of-conduct.vue

**Comment by eruizc-dev** [comment]
Done in #51 and #56
