### ISSUE TITLE
Improve Navbar styles focusing in contrast/UX etc.

### ISSUE THREAD

**Issue by mvargasmoran** [vim-conf-live/NeoVimconf-site-2022#38]
This is pertaining this nice catch By @eruizc-dev 
I think he is right we should do something about the Navbar, it was perfect for starters but now it's time to take shape.

https://github.com/vim-conf-live/NeoVimconf-site-2022/pull/37#issuecomment-1284101867

**Comment by isaif** [comment]
As @eruizc-dev said we can get rid of the stickiness of the navbar. Sticky navbar makes more sense when we have a lot of sections and we add links to those sections in navbar for quick scroll.

**Comment by eruizc-dev** [comment]
We are going to have schedule, speakers, and sponsor sections

**Comment by isaif** [comment]
There is not much space left in mobile version of navbar.

What are we going to do for mobile?

A menu?

**Comment by eruizc-dev** [comment]
Menus require an extra tap, maybe just hide/shorten some things like this:
![image](https://user-images.githubusercontent.com/58179604/197403298-65cf09ca-2e24-4911-8c24-d233cd143b6c.png)
