### ISSUE TITLE
live countdown timer

### ISSUE THREAD

**Issue by AdamBD** [vim-conf-live/NeoVimconf-site-2022#85]

**Comment by AdamBD** [comment]
The event will begin 12pm EST On december 9th. We should have a countdown clock which ticks till then

**Comment by mvargasmoran** [comment]
@lahnie let's check the mobile view, adjust the event date, and let's called it done.

**Comment by mvargasmoran** [comment]
@lahnie I merged the Pull Request for this task, please close it if there's nothing else to do with it.
